---
title: "Exploring Heart Attack Data"
---


```{r}
# read the csv file and save as a variable called heart_data
heart_data <- read.csv("../data/heart_attack_data.csv")
```

```{r}
# preview the data
head(heart_data)
```

```{r}
# class of the variable
class(heart_data)
```
```{r}
# number of rows and columns
dim(heart_data)
```

```{r}
# structure of the data frame
str(heart_data)

# int and num are numerical variables.
```

```{r}
# factorise the variables that should be categorised

heart_data$sex <- factor(heart_data$sex)
heart_data$cp <- factor(heart_data$cp)
heart_data$fbs <- factor(heart_data$fbs)
heart_data$restecg <- factor(heart_data$restecg)
heart_data$exang <- factor(heart_data$exang)
heart_data$target <- factor(heart_data$target)
```

```{r}
# check the structure of the data frame again and make sure they are factorised

str(heart_data)
```

```{r}
# number of patients with heart disease

summary(heart_data$target)
```

```{r}
# number of patients with heart disease by gender

table(heart_attack_data$sex, heart_attack_data$target)
```
```{r}
# tidy up the table
heart_disease_dist <- as.data.frame(table(heart_attack_data$sex, heart_attack_data$target))
colnames(heart_disease_dist) <- c("Gender", "Target", "Frequency")
heart_disease_dist
```
```{r}
# convert the 0s to map to female and 1st to male
library(dplyr)
heart_disease_dist >%>
  mutate()
heart_disease_dist
```

```{r}
library(tidyverse)
ggplot(heart_disease_dist, aes(x=Gender, y=Frequency, fill=Target)) +
  geom_col() +
  labs(title="Distribution of Heart Disease by Gender")

# reference: https://rpubs.com/murraylax/viscrosstabs
```
