---
title: "Using SQL to Query Data"
---

```{r}
# connecting to a database that we have currently stored in our data folder

library(DBI)

filename <- "../data/prod_sample.db"
my_connection <- dbConnect(RSQLite::SQLite(),
                dbname = filename)
my_connection
```


```{r}
## Check what tables exist in this database
dbListTables(my_connection)

# we have two tables that exist in our database
```


```{sql connection=my_connection}
/* sql query to view the first ten rows of the online_retail_history table - be sure to pass in the connection */
select *
from online_retail_history
limit 10
```

```{sql connection=my_connection}
/* write a sql query that left joins the stock_description table to the online_retail_history table  */
select t1.*,
       t2.Description
from online_retail_history t1
left join stock_description t2 on t1.StockCode = t2.StockCode
```


```{sql connection=my_connection}
/* write a sql query to calculate the unique number of products sold*/
select count(distinct StockCode) as number_products
from online_retail_history
```

```{sql connection=my_connection}
/* write a sql query that identifies the top 20 best selling products in Germany */

select t2.Description,
      sum(t1.quantity) as total_quantity
from online_retail_history t1
join stock_description t2 on t1.StockCode = t2.StockCode
/*the <> means not equal*/
where Country = 'Germany' and Description NOT IN ('?', 'POSTAGE')
group by t2.Description
order by total_quantity desc
limit 20
```


```{sql connection=my_connection}
/* write a sql query that identifies the country with the most customers */
select Country,
      count(distinct CustomerID) as number_unique_customers
from online_retail_history 
group by Country
order by 2 desc
limit 10
```

```{sql connection=my_connection}
/*write a sql query that gives the number of invoices per year*/

/*we need to extract the year from the InvocieDate*/

select cast(strftime('%Y', InvoiceDate) as integer) as year,
                   count(distinct Invoice) as number_purchases
from online_retail_history
group by year

```
```{sql connection=my_connection}
/*write a sql query that identifies the months with the highest sales in 2011*/
/*we need to extract the month from the InvocieDate*/

select cast(strftime('%m', InvoiceDate) as integer) as month,
                   sum(Quantity) as number_purchases
from online_retail_history
where cast(strftime('%Y', InvoiceDate) as integer) = 2011
group by month
order by number_purchases desc

/*November had the most sales, followed by October*/
```
```{sql connection=my_connection}
/*write a sql query that identifies the day of the week with the highest sales in 2011*/
/*we need to extract the day of the week from the InvocieDate*/

select cast(strftime('%w', InvoiceDate) as integer) as dow,
       sum(Quantity) as number_purchases
from online_retail_history
where cast(strftime('%Y', InvoiceDate) as integer) = 2011
group by dow
order by number_purchases desc

/*Day 4 has the highest highest sales - but what is day 4?*/
```
```{sql connection=my_connection}
/*write a sql query that maps the weekday number to the name of the week*/

select distinct cast(strftime('%w', InvoiceDate) as integer) as dow,
       case cast (strftime('%w', InvoiceDate) as integer)
                      when 0 then 'Sunday'
                      when 1 then 'Monday'
                      when 2 then '???'
                      when 3 then '???'
                      when 4 then '???'
                      when 5 then '???'
                      else 'Saturday' end as weekday
from online_retail_history

```
```{sql connection=my_connection}
/*write a sql query that maps the month number to the name of the month*/

select distinct cast(strftime('%m', InvoiceDate) as integer) as dow,
       case cast (strftime('%m', InvoiceDate) as integer)
                      when 1 then 'January'
                      when 2 then 'February'
                      when 3 then '???'
                      when 4 then '???'
                      when 5 then '???'
                      when 6 then '???'
                      when 7 then '???'
                      when 8 then '???'
                      when 9 then '???'
                      when 10 then '???'
                      when 11 then '???'
                      else 'December' end as weekday
from online_retail_history

```


```{sql connection=my_connection}
/*write a sql query that gives the number of invoices per month per day of week for the year 2011*/

select cast(strftime('%m', InvoiceDate) as integer) as month,
                  case cast (strftime('%w', InvoiceDate) as integer)
                      when 0 then 'Sunday'
                      when 1 then 'Monday'
                      when 2 then 'Tuesday'
                      when 3 then 'Wednesday'
                      when 4 then 'Thursday'
                      when 5 then 'Friday'
                      else 'Saturday' end as weekday,
                   sum(Quantity) as number_purchases
                from online_retail_history
            where cast(strftime('%Y', InvoiceDate) as integer) = 2011
            group by month, weekday
            order by month, number_purchases desc
```


```{r}
# Plot the number of distinct customers per country using sql queries

# import the library
library(tidyverse)

# write the SQL query in the paste function and store as a variable called query
query <- paste("
select Country,
      count(distinct CustomerID) as number_unique_customers
from online_retail_history 
group by Country
order by 2 desc
limit 10",
sep = "" )

# pass your connection and the query to the tbl function and store as a variable
customers_per_country <- tbl(my_connection, sql(query))
customers_per_country

```
```{r}
customers_per_country %>%
  ggplot(aes(x=reorder(Country, -number_unique_customers), y = number_unique_customers)) +
    geom_bar(stat = 'identity', color="black", fill="blue") +
      xlab('Country') +
        ylab('Number of Unique Customers') +
          ggtitle("Distribution of Countries by Customers") 
```
```{r}
# Plot the distribution of best selling products

# write the SQL query in the paste function and store as a variable called query
query <- paste("
select t2.Description,
      sum(t1.quantity) as total_quantity
from online_retail_history t1
join stock_description t2 on t1.StockCode = t2.StockCode
/*the <> means not equal*/
where Description NOT IN ('?', 'POSTAGE') and
  cast(strftime('%Y', InvoiceDate) as integer) = 2011
group by t2.Description
order by total_quantity desc
limit 20",
sep = "" )

# pass your connection and the query to the tbl function and store as a variable
top_products <- tbl(my_connection, sql(query))
top_products

```
```{r}
top_products %>%
  ggplot(aes(x=reorder(Description, -total_quantity), y = total_quantity)) +
    geom_bar(stat = 'identity', color="white", fill="pink") +
      xlab('Country') +
        ylab('Total Sales') +
          ggtitle("Top 20 Products by Total Sales in 2011") +
            theme(axis.text.x = element_text(angle = 90, size = 8))
```
```{r}
# Plot the distribution of best selling products

# write the SQL query in the paste function and store as a variable called query
query <- paste("
?????",
sep = "" )

# pass your connection and the query to the tbl function and store as a variable
top_products <- tbl(my_connection, sql(query))
top_products

```


```{r}
dbDisconnect(my_connection)
```



