---
title: "Using SQL to Query Data"
---

```{r}
# connecting to a database that we have currently stored in our data folder

library(DBI)

filename <- "../data/prod_sample.db"
my_connection <- dbConnect(RSQLite::SQLite(),
                dbname = filename)
my_connection
```


```{r}
## Check what tables exist in this database
dbListTables(my_connection)

# we have two tables that exist in our database
```


```{sql connection=my_connection}
/* sql query to view the first ten rows of the online_retail_history table - be sure to pass in the connection */
select *
from online_retail_history
limit 10
```

```{sql connection=my_connection}
/* write a sql query to view the first five rows of the stock_description table - be sure to pass in the connection */
select *
from stock_description
limit 5
```

```{sql connection=my_connection}
/* write a sql query to count how many rows the online_retail_history table contains */
select count(*) as number_rows
from online_retail_history 
```

```{sql connection=my_connection}
/* write a sql query to count how many rows the stock_description table contains */
select count(*) as number_rows
from stock_description
```


```{sql connection=my_connection}
/* write a sql query to calculate the min and max invoice*/
select min(InvoiceDate) as min_invoice_date,
       max(InvoiceDate) as min_invoice_date
from online_retail_history

/*5 million items sold*/
```

```{sql connection=my_connection}
/* write a sql query to calculate the average price of products sold*/
select avg(Price) as avg_price
from online_retail_history
where country = 'United Kingdom'

/*average price of item is 4.5 pounds*/
```

```{sql connection=my_connection}
/* write a sql query to select the CustomerID Columns*/
select CustomerID
from online_retail_history
```
```{sql connection=my_connection}
/* write a sql query to select the distinct CustomerIDs from CustomerID Column*/
select distinct CustomerID
from online_retail_history
```
```{sql connection=my_connection}
/* write a sql query to count the unique number of customers*/
select count(distinct CustomerID) as number_unique_customers
from online_retail_history
```
```{sql connection=my_connection}
/* write a sql query to count the unique number of customers per country*/
select Country,
       count(distinct CustomerID) as number_unique_customers
from online_retail_history
group by Country
```
```{sql connection=my_connection}
/* write a sql query to count the unique number of customers per country*/
select Country
from online_retail_history
group by Country
order by count(distinct CustomerID) desc
limit 1
```

```{sql connection=my_connection}
/* write a sql query to calculate the number of unique Invoices*/
select count(distinct Invoice) as number_invoices
from online_retail_history
```

```{sql connection=my_connection}
/* write a sql query to calculate the number of unique stock codes in the online_retail_history table*/
select count(distinct StockCode) as number_unique_stocks
from online_retail_history
```

```{sql connection=my_connection}
/* write a sql query to calculate the number of unique stock codes in the online_retail_history table*/
select count(distinct StockCode) as number_unique_stocks
from stock_description

/*why would the different tables contain different stock codes?*/
```
```{sql connection=my_connection}
/* write a sql query to count stocks with the description ? */
select count(Description)
from stock_description
where Description = "?"
```
```{sql connection=my_connection}
/* write a sql query to count invoices with negative price and quantity */
select count(distinct Invoice) as number_invoices
from online_retail_history
where quantity < 0 or price < 0
```

```{sql connection=my_connection}
/* write a sql query to calculate the number of unique stock codes in the online_retail_history table*/
select StockCode,
       sum(Quantity) as total_purchased
from online_retail_history
group by StockCode
order by total_purchased desc
limit 1
```
```{sql connection=my_connection}
/* write a sql query to calculate the number of unique stock codes in the online_retail_history table*/
select Description
from stock_description
where StockCode = "22197"
```

```{r}
dbDisconnect(my_connection)
```



